version: '3.8'

services:
  bookmarks-server:
    build: ./docker
    container_name: bookmarks-server
    # Port mapping removed - use docker-compose.nginx-proxy.yml for Nginx Proxy Manager
    # ports:
    #   - "${PORT:-9080}:9080"
    volumes:
      # Mount bookmarks data directory
      - ./docker/data:/data/bookmarks:rw
      # Mount logs directory
      - ./docker/logs:/data/logs:rw
      # Mount configuration (optional)
      - ./.bookmarks.env:/app/.bookmarks.env:ro
    environment:
      - BOOKMARKS_DIR=/data/bookmarks
      - DEBUG=${DEBUG:-INFO}
      - PORT=9080
      - LOG_FILE=/data/logs/bookmarks-server.log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bookmarks-network
    # No reverse proxy labels - use Nginx Proxy Manager web interface for configuration

networks:
  bookmarks-network:
    driver: bridge

volumes:
  bookmarks-data:
    driver: local 